### ISSUE TITLE
Invalid uuid exception after upgrade from 0.1.2 to 0.2.1

### ISSUE THREAD

**Issue by fuse314** [michib/nextcloud_twofactor_webauthn#35]
The app cannot be enabled again:
- With the app activated, the occ upgrade fails with
```
>>occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <twofactor_webauthn> ...
Ramsey\Uuid\Exception\InvalidUuidStringException: Invalid UUID string:
Update failed
Maintenance mode is kept active
Reset log level
```                                                                                                                              
after disabling the app with occ and turning maintenance mode off, I can not enable the app in the web interface with the same exception:
```
Invalid UUID string:
```
How can I get the app back in a working state?
Maybe I can clear the existing data from the database?

I am using Nextcloud 17.0.4 within a docker container.

**Comment by michib** [comment]
Yes, deleting the contents of twofactor_webauthn_registrations would clear this error.

But could you post the contents of the nextcloud server log, regarding the exception which occurred during the update? 
And could you send me the sql dump or the content of the aaguid column? That would be great to fix the migration bug

**Comment by AdmiralNemo** [comment]
[twofactor_webauthn-error.json.log](https://github.com/michib/nextcloud_twofactor_webauthn/files/4360912/twofactor_webauthn-error.json.log)

I have the same issue.  I've attached the error message from `nextcloud.log`.

None of the records in `oc_twofactor_webauthn_registrations` have a value in the `aaguid` field.

**Comment by AdmiralNemo** [comment]
I was able to work around this issue by running

```
UPDATE oc_twofactor_webauthn_registrations SET aaguid = NULL WHERE aaguid = '';
``

**Comment by michib** [comment]
oh an empty string is surprising, there should have been a 16 characters long empty string. But thanks for the feedback.
Can you tell me which webauthn devices you are using?

**Comment by AdmiralNemo** [comment]
I currently have 1 Somu and 2 Solo Tap devices registered.

**Comment by AdmiralNemo** [comment]
Although I was able to proceed with the upgrade using [the above work-around](https://github.com/michib/nextcloud_twofactor_webauthn/issues/35#issuecomment-601811415), I am not able to actually use any of my WebAuthn devices any more:

```
$bytes string should contain 16 characters.
```

**Comment by michib** [comment]
Yeah i was already surprised it works with null.
As a Workaround, can you insert '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0' into the aaguid columns? This should help.
Would you be so kind to test this first, because this would be helpful for my bugfix.
Afterwards, can you test if you can remove and readd one of your devices and check if it is possible to authenticate with this device?

**Comment by AdmiralNemo** [comment]
I couldn't figure out how to put null bytes in the field, but it turns out that no matter what I put in there, as long as its 16 characters, everything works fine.

```
UPDATE oc_twofactor_webauthn_registrations SET aaguid = '0123456789abcdef'
```

I can also confirm that removing and re-registering my Somu resulted in an empty string for `aaguid` with the latest version of this app.

**Comment by michib** [comment]
I released 0.2.2 which should handle this issue. Please reopen this issue, if it's not the case.
And great thanks for your effort of testing this provider!

**Comment by AdmiralNemo** [comment]
After updating to 0.2.2, I still get the `$bytes string should contain 16 characters` error.  I deleted and re-registered my devices, and they have still have empty strings in the `aaguid` column.

**Comment by michib** [comment]
@AdmiralNemo with empty string for the `aaguid` column, you mean length 0 or is it length 16? Just to be sure.
Could you open a new issue for this case? It would be great, if you could send me the response of the post to <nextcloud-host>/apps/twofactor_webauthn/settings/finishregister. I'm interested on the data field of the body.

**Comment by AdmiralNemo** [comment]
I've opened #36 to continue the discussion.
